clone_depth: 200

environment:
  matrix:
    - QTDIR: C:\Qt\5.10.1\msvc2013_64

configuration: Release

install:
  - choco install -y qbs --version 1.10.1

build_script:
  - qbs setup-toolchains --detect
  - qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - qbs config defaultProfile qt
  - cd test
  - qbs build
  - qbs run
